### 메뉴 추가
POST localhost:8080/api/menus
Content-Type: application/json

{
  "name": "김밥",
  "category": "분식",
  "price": 2000,
  "description": "계란이 많아요"
}

### 메뉴 추가
POST localhost:8080/api/menus
Content-Type: application/json

{
  "name": "돈까스",
  "category": "일식",
  "price": 5000,
  "description": "돼지고기"
}

### 메뉴 추가
POST localhost:8080/api/menus
Content-Type: application/json

{
  "name": "생선까스",
  "category": "일식",
  "price": 5000,
  "description": "돼지고기"
}

### 메뉴 추가
POST localhost:8080/api/menus
Content-Type: application/json

{
  "name": "떡볶이",
  "category": "일식",
  "price": 5000,
  "description": "돼지고기"
}

### 가게 추가
POST localhost:8080/api/shops
Content-Type: application/json

{
  "name": "엄마김밥",
  "address": "주소",
  "contactNumber": "010-0000-0000"
}

### 가게 추가
POST localhost:8080/api/shops
Content-Type: application/json

{
  "name": "아들분식",
  "address": "주소",
  "contactNumber": "010-0000-0000"
}


### 고객 추가
POST localhost:8080/api/consumers
Content-Type: application/json

{
  "name": "조현창",
  "address": "주소",
  "contactNumber": "010-0000-0000"
}

### 주문 추가
POST localhost:8080/api/orders
Content-Type: application/json

{
  "consumerId": 1,
  "shopId": 1,
  "items": [{
    "menuId": 1,
    "qty": 10
  }, {
    "menuId": 2,
    "qty": 10
  }, {
    "menuId": 3,
    "qty": 10
  }]
}

### 주문 추가
POST localhost:8080/api/orders
Content-Type: application/json

{
  "consumerId": 1,
  "shopId": 1,
  "items": [{
    "menuId": 2,
    "qty": 10
  }, {
    "menuId": 3,
    "qty": 10
  }]
}

### 주문 추가
POST localhost:8080/api/orders
Content-Type: application/json

{
  "consumerId": 1,
  "shopId": 1,
  "items": [{
    "menuId": 3,
    "qty": 10
  }]
}


### 전체 주문 조회
GET localhost:8080/api/orders
Accept: application/json


### 전체 주문 조회
GET localhost:8080/api/orders
Accept: application/json

### 주문 완료
PATCH localhost:8080/api/orders/1/status
Content-Type: application/json

{
  "status": "COMPLETED"
}

### 주문 완료
PATCH localhost:8080/api/orders/2/status
Content-Type: application/json

{
  "status": "COMPLETED"
}

### 주문 완료
PATCH localhost:8080/api/orders/3/status
Content-Type: application/json

{
  "status": "COMPLETED"
}


### 전체 주문 조회
GET localhost:8080/api/orders
Accept: application/json

### 전체 가게 매출 조회
GET localhost:8080/api/shops/revenues
Accept: application/json

### 인기 메뉴 조회
GET localhost:8080/api/menus/ranks
Accept: application/json